config/routes.rb
Roobb::Application.routes.draw do
  devise_for :users, :skip => :delete

  resources :categories, :path => 'category', :only => [:show, :new, :create] , :controller => 'category' do
    resources :topics, :path => 'topic', :only => [:show, :new, :create] , :controller => 'topic' do
      member do
        post 'save_subject'
        delete 'delete', :action => 'delete'
        get 'delete', :action => 'confirm_delete'
        get 'restore'
        get 'close'
      end
      resources :posts, :controller => 'post' do
          member do
            get 'get_raw'
            put 'save_edit'
            delete 'delete', :action => 'delete'
            get 'delete', :action => 'confirm_delete'
            get 'restore', :action => 'restore'
          end
      end
    end
  end

  resources :users

  root :to => 'category#list'

end

app/models/category.rb
class Category < ActiveRecord::Base

  attr_accessible :name, :post_count, :topic_count_count
  validates :name, presence: true
  before_save :set_stats
  has_many :topics

  def to_param
    "#{id}-#{name.parameterize}"
  end

  protected

  def set_stats
    if self.new_record?
      self.post_count = 0
      self.topic_count = 0
    end
  end

end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

  load_and_authorize_resource :only => [:new, :create]

  def list
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @topics = Topic.scoped_by_category_id(@category.id).order('updated_at DESC').page(params[:page])
    add_breadcrumb @category.name, category_path(@category)
  end

  def new
    @category = Category.new()
    add_breadcrumb t('category.create')
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to '/'
      flash[:success] = t('category.created')
    else
      render :action => 'new'
    end
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/category/_category_row.erb
<li class="media">
    <div class="row">
        <div class="span8">
            <h4>
                <a href="<%= category_path(category) %>" rel="tooltip" data-placement="right" data-original-title="<%= pluralize category.topics.count, t('topic.topic') %>"><%= category.name %></a>
            </h4>
        </div>
        <div class="span4 recent-cat-list">
            <ul>
                <% category.topics.order("updated_at DESC").limit(3).each do |topic| %>
                    <li><a href="<%= category_topic_path(category, topic) %>"><%= topic.subject %></a> (<%= time_ago_in_words topic.updated_at %>)</li>
                <% end %>
            </ul>
        </div>
    </div>
</li>

app/views/category/_form.erb
<%= form_for @category do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.submit %>
<% end %>

app/views/category/_topic_row.erb
<tr class="<%= get_topic_class (topic) %>">
    <td>
        <% if topic.deleted %>
            <a href="#" rel="tooltip" data-placement="top" data-original-title="<%= t('topic.deleted') %>"><i class="icon-minus-sign"></i></a>
        <% elsif topic.closed %>
            <a href="#" rel="tooltip" data-placement="top" data-original-title="<%= t('topic.closed') %>"><i class="icon-lock"></i></a>
        <% end %>
        <% if topic.deleted && !can?(:delete, topic) %>
            <%= get_topic_line(topic) %>
        <% else %>
            <%= link_to get_topic_line(topic), [@category, topic] %>
        <% end %>
    </td>
    <td style="text-align: center;">
        <%= topic.posts_count %>
    </td>
    <td style="text-align: center;">
        <% if topic.updated_at < 1.day.ago %>
            <%= topic.updated_at.strftime("%m/%d/%Y") %>
        <% else %>
            <%= time_ago_in_words(topic.updated_at) + ' ' + t('ago') %>
        <% end %>

    </td>
</tr>

app/views/category/list.erb
<div class="well">
    <h3><%= t('index.welcome') %></h3>
    <%= t('index.welcome_notice') %>
</div>
<%= cache @categories, :expires_in => 5.minutes do %>
    <div class="category-list">
        <ul class="media-list">
            <% @categories.each() do |category| %>
                <%= render :partial => 'category_row', :locals => {:category => category} %>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="row">
    <div class="span12">
        <% if can? :create, Category %>
            <%= link_to t('category.create'), '/category/new', :class => 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/category/new.erb
<h3><%= t('category.create') %></h3>

<%= render :partial => 'form' %>

app/views/category/show.erb
<div class="row">
    <div class="span9">
        <h4><%= @category.name %></h4>
    </div>
    <div class="span3">
        <% if can? :create, Topic %>
            <%= link_to t('topic.create'), new_category_topic_path(@category), :class => 'btn btn-primary pull-right' %>
        <% end %>
    </div>
</div>

<table class="table table-striped table-hover topic_list">
    <thead>
        <tr>
            <th style="width: 70%;">
                Subject
            </th>
            <th style="text-align: center;">
                Posts
            </th>
            <th style="text-align: center;">
                Last post
            </th>
        </tr>
    </thead>
    <tbody>
        <% @topics.each() do |topic| %>
            <%= render :partial => 'topic_row', :locals => {:topic => topic} %>
        <% end %>
    </tbody>

</table>

<%= paginate @topics %>