config/routes.rb
Roobb::Application.routes.draw do
  devise_for :users, :skip => :delete

  resources :categories, :path => 'category', :only => [:show, :new, :create] , :controller => 'category' do
    resources :topics, :path => 'topic', :only => [:show, :new, :create] , :controller => 'topic' do
      member do
        post 'save_subject'
        delete 'delete', :action => 'delete'
        get 'delete', :action => 'confirm_delete'
        get 'restore'
        get 'close'
      end
      resources :posts, :controller => 'post' do
          member do
            get 'get_raw'
            put 'save_edit'
            delete 'delete', :action => 'delete'
            get 'delete', :action => 'confirm_delete'
            get 'restore', :action => 'restore'
          end
      end
    end
  end

  resources :users

  root :to => 'category#list'

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  attr_accessible :forum_id, :last_post, :subject
  has_many :posts
  belongs_to :category
  belongs_to :user
  validates :subject, presence: true
  validates :user_id, presence: true
  validates_length_of :subject, :maximum => 25

  def to_param
    "#{id}-#{self.subject.parameterize}"
  end

end

app/controllers/topic_controller.rb
class TopicController < ApplicationController

  load_and_authorize_resource :only => [:new, :create]

  def show
    @topic = Topic.includes('category').find(params[:id])
    @category = @topic.category
    @posts = Post.scoped_by_topic_id(@topic.id).order(:created_at).page(params[:page]).includes(:user)
    @post = Post.new
    @post.topic = @topic
    add_breadcrumb @category.name, @category
    add_breadcrumb @topic.subject
  end

  def new
    @category = Category.find(params[:category_id])
    @topic = Topic.new
    @post = Post.new
    add_breadcrumb @category.name, @category
    add_breadcrumb t('topic.create')
  end

  def create
    @category = Category.find(params[:category_id])
    @topic = Topic.new(params[:topic])
    @topic.category_id = @category.id
    @topic.posts.build(params[:post])
    @topic.user_id = current_user.id
    @topic.posts[0].user_id = current_user.id
    if @topic.save
      redirect_to [@category, @topic]
      flash[:success] = t('topic.created')
    else
      @post = @topic.posts[0]
      render :action => 'new'
    end
  end

  def save_subject
    @topic = Topic.find(params[:id])
    authorize! :update, @topic
    @topic.subject = params[:subject]
    if @topic.save
      render_alert :success, t('topic.subject_updated')
    else
      render_alert :error, t('error')
    end

  end

  def delete
    @topic = Topic.includes(:category).find(params[:id])
    authorize! :delete, @topic
    @topic.deleted = true
    @topic.deleted_message = params[:topic][:deleted_message]
    if @topic.save
      flash[:success] = t('topic.deleted')
    else
      flash[:error] = t('error')
    end
    redirect_to [@topic.category, @topic]
  end

  def confirm_delete
    @topic = Topic.includes(:category).find(params[:id])
    authorize! :delete, @topic
    render :partial => 'confirm_delete'
  end

  def restore
    @topic = Topic.includes(:category).find(params[:id])
    authorize! :delete, @topic
    @topic.deleted = false
    @topic.deleted_message = ''
    if @topic.save
      flash[:success] = t('topic.restored')
    else
      flash[:error] = t('error')
    end
    redirect_to [@topic.category, @topic]
  end

  def close
    @topic = Topic.includes('category').find(params[:id])
    authorize! :delete, @topic

    @topic.toggle :closed

    if @topic.save
      if @topic.closed
        flash[:success] = t('topic.closed')
      else
        flash[:success] = t('topic.opened')
      end
    else
       flash[:error] = t('error')
    end
    redirect_to [@topic.category, @topic]
  end
end

app/helpers/topic_helper.rb
module TopicHelper
  def get_topic_line (topic)
    text = topic.subject
    if topic.deleted && !topic.deleted_message.empty?
      text += ' - ' + topic.deleted_message
    end
    return text
  end

  def get_topic_class (topic)
    if topic.deleted
      return 'deleted'
    elsif topic.closed
      return 'closed'
    end
    return ''
  end
end

app/views/topic/_confirm_delete.erb
<%= form_for [@topic.category, @topic],
             :method => 'delete', :url => {:action => 'delete'}, :html => {:class => 'delete_form'} do |form| %>
    <div class="modal-body">
        <div class="form">
            <h4><%= t('post.delete_message') %></h4>

            <p>
                <%= form.text_field :deleted_message, {'placeholder' => t(:delete_placeholder)} %>
            </p>
        </div>
    </div>
    <div class="modal-footer">
        <a href="#" data-dismiss="modal" class="btn">Cancel</a>
        <% if @topic.deleted %>
            <button type="submit" value="submit" class="btn delete-submit">Update message</button>
            <a href="<%= restore_category_topic_post_path %>" class="btn btn-success delete-submit">Restore</a>
        <% else %>
            <button type="submit" value="submit" class="btn btn-danger">Delete</button>
        <% end %>
    </div>
<% end %>

app/views/topic/_form.erb
<%= form_for [@category, @topic] do |form| %>
    <% if @topic.errors.any? %>
        <div class="alert error">
            <ul>
                <% @topic.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <%= form.label :subject %>
    <%= form.text_field :subject %>

    <%= fields_for @post do |postform| %>
        <%= postform.label :body %>
        <%= postform.text_area :body %>
    <% end %>
    <br/>
    <%= form.submit %>
<% end %>

app/views/topic/_post.erb
<div id="post-<%= post.id %>" class="post-block container-fluid thumbnail">
    <% if post.user.id == @topic.user_id %>
        <div class="op_block">
            <a href="#" rel="tooltip" data-placement="right" data-original-title="<%= t('op_full') %>"><%= t('op') %></a>
        </div>
    <% end %>
    <div class="row-fluid">
        <div class="post-profile-block span2">
            <%= render :partial => 'post_profile', :locals => {:user => post.user} %>
        </div>
        <div class="post-body-block span10">
            <div class="post-body-wrap">
                <%= raw(post.parsed_body) %>
            </div>
            <div class="edit-post-wrap"></div>
            <div class="post-options-block">
                <div class="btn-group">
                    <span class="btn btn-small">
                        <% if post.created_at < 1.day.ago %>
                            <%= post.created_at.strftime("%m/%d/%Y") %>
                        <% else %>
                            <%= time_ago_in_words(post.created_at) + ' ' + t('ago') %>
                        <% end %>
                    </span>
                    <% if can? :create, @post %>
                        <a href="#new-post-block" class="btn btn-small reply_button" rel="tooltip" data-id="<%= post.id %>" data-user="<%= post.user.username %>" data-placement="top" data-original-title="<%= t('quote') %>">
                            <i class="icon-comment"></i>
                        </a>
                    <% end %>
                    <% if current_user.present? %>
                        <a href="javascript:void(0)" class="btn btn-small report_button" rel="tooltip" data-path="<%= get_raw_category_topic_post_path(@category, @topic, post) %>" data-placement="top" data-original-title="<%= t('report') %>">
                            <i class="icon-flag"></i>
                        </a>
                    <% end %>
                    <% if can? :update, post %>
                        <a href="javascript:void(0)" class="btn btn-small edit_button" rel="tooltip" data-path="<%= get_raw_category_topic_post_path(@category, @topic, post) %>" data-placement="top" data-original-title="<%= t('edit') %>">
                            <i class="icon-pencil"></i>
                        </a>
                    <% end %>
                    <% if can? :destroy, post %>
                        <a href="javascript:void(0)" class="btn btn-small delete_trigger" rel="tooltip" data-path="<%= delete_category_topic_post_path(@category, @topic, post) %>" data-placement="top" data-original-title="<%= t('delete') %>">
                            <i class="icon-remove"></i>
                        </a>
                    <% end %>
                </div>
            </div>

        </div>

    </div>
    <div class="clearfix"></div>
</div>

app/views/topic/_post_deleted.erb
<div class="post-deleted">
    <div class="header">
        <% if can? :delete, post %>
            <a href="javascript:void(0)" class="show-deleted-post">
        <% end %>
        <%= t('post.deleted') %> -
    <span class="reason">
        <%= post.deleted_message %>
    </span>
        <% if can? :delete, post %>
            </a>
        <% end %>
    </div>


    <% if can? :delete, post %>
        <%= render :partial => 'post', :locals => {:post => post} %>
    <% end %>

</div>

app/views/topic/_post_profile.erb
<%= gravatar_image_tag(user.email, :alt => user.username) %>
<br/>
<%= link_to user.username, user %>

app/views/topic/new.erb
<%= render :partial => 'form' %>

app/views/topic/show.erb
<div class="subject">

    <% if can? :update, @topic %>
        <div class="edit-subject-block">
            <a href="javascript:void(0)"
               class="subject-link-wrap"
               rel="popover"
               data-placement="left"
               data-html="true"
               data-url="<%= save_subject_category_topic_path(@category, @topic) %>"
               data-trigger="manual"
               data-container=".subject-link-wrap"
               data-content="<a href=&quot;#&quot; class=&quot;btn btn-success&quot; id=&quot;save-subject&quot;>Save</a>">
                <input class="span5" type="text" value="<%= @topic.subject %>" maxlength="25"/>
            </a>
        </div>
    <% else %>
        <h2>
            <%= @topic.subject %>
        </h2>
    <% end %>
</div>

<%= paginate @posts %>
<% @posts.each() do |post| %>
    <% if !post.deleted %>
        <%= render :partial => 'post', :locals => {:post => post} %>
    <% else %>
        <%= render :partial => 'post_deleted', :locals => {:post => post} %>
    <% end %>
<% end %>
<%= paginate @posts %>
<div id="new-post-block" class="tabs-below">
    <% if can? :create, @post %>
        <h3><%= t('topic.new_post') %></h3>

        <%= form_for [@category, @topic, @post] do |form| %>
            <%= form.text_area :body, {'class' => 'span12', 'rows' => 8} %>
            <br/>
            <%= form.submit %>
        <% end %>
        <div class="nav nav-tabs">
            <li class="pull-right">
                <a href="<%= close_category_topic_path(@category, @topic) %>">
                    <% if @topic.closed %>
                        <%= t('topic.open') %>
                    <% else %>
                        <%= t('topic.close') %>
                    <% end %>
                </a>
            </li>
            <li class="pull-right">
                <% if @topic.deleted %>
                    <a href="<%= restore_category_topic_path(@category, @topic) %>">
                        <%= t('topic.restore') %>
                    </a>
                <% else %>
                    <a id="thread-delete" data-url="<%= delete_category_topic_path(@category, @topic) %>" href="javascript:void(0)">
                        <%= t('topic.delete') %>
                    </a>
                <% end %>

            </li>
        </div>
    <% end %>
</div>

<div id="delete-modal" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3><%= t('post.delete_confirm') %></h3>
    </div>
    <div class="modal-payload">

    </div>
</div>