config/routes.rb
Roobb::Application.routes.draw do
  devise_for :users, :skip => :delete

  resources :categories, :path => 'category', :only => [:show, :new, :create] , :controller => 'category' do
    resources :topics, :path => 'topic', :only => [:show, :new, :create] , :controller => 'topic' do
      member do
        post 'save_subject'
        delete 'delete', :action => 'delete'
        get 'delete', :action => 'confirm_delete'
        get 'restore'
        get 'close'
      end
      resources :posts, :controller => 'post' do
          member do
            get 'get_raw'
            put 'save_edit'
            delete 'delete', :action => 'delete'
            get 'delete', :action => 'confirm_delete'
            get 'restore', :action => 'restore'
          end
      end
    end
  end

  resources :users

  root :to => 'category#list'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Roobb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>


<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to t(:title), '/', :class => 'brand' %>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active"><a href="#"><%= t('nav.home') %></a></li>
                    <li><%= link_to t('nav.members'), users_path %></li>
                </ul>
                <ul class="nav pull-right">
                    <% if user_signed_in? %>
                        <li class="dropdown">
                            <%= link_to raw(t('account.profile') + '<b class="caret"></b>'), edit_user_registration_path, :class => 'dropdown-toggle', :data => {:toggle => 'dropdown'} %>
                            <ul class="dropdown-menu">
                                <li><%= link_to t('nav.account'), edit_user_registration_path %></li>
                                <li><%= link_to t('account.logout'), destroy_user_session_path, :method => :delete %></li>
                            </ul>
                        </li>
                    <% else %>
                        <li><%= link_to t('account.signin'), new_user_session_path %></li>
                    <% end %>

                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container">
    <div class="flash-wrap">
        <%= bootstrap_flash %>
    </div>
    <%= render_breadcrumbs %>

    <%= yield %>

</div>
<!-- /container -->
</body>
</html>